steps:
  - command: "./build.sh"
    label: "Compile"
    artifact_paths:
      - "build/*"
  - wait
  - command: "./test.sh"
    label: "Tests"
    if: build.message !~ /no test/
  - command: "./deploy.sh"
    label: "Package"
    if: build.message =~ /launch deploy/